### ISSUE TITLE
util/compile-module的问题

### ISSUE THREAD

**Issue by leowang721** [ecomfe/edp-build#68]
@leeight

在util/compile-module.js中，line 51左右
```javascript
var code = compileModule(
    fs.readFileSync(depFile, 'UTF-8'),
    depId,
    moduleConfig,
    ...
```

这里是直接fs read的文件内容，也就是说，不能够前置的修改context中的fileInfo的data来达到修改内容的目的……

是不是应该修改为processContext获取，获取失败再fs read？

**Comment by leeight** [comment]
已经处理了，参考 https://github.com/ecomfe/edp/issues/325
