### ISSUE TITLE
edp-build为啥依赖edpx-bcs

### ISSUE THREAD

**Issue by errorrik** [ecomfe/edp-build#69]

**Comment by zengjialuo** [comment]
噢，好像是我加的，因为有个 bcsUploaderProcessor 用到了 bcs...

**Comment by leeight** [comment]
那要不就去掉吧？

**Comment by leeight** [comment]
去掉了这个依赖，如果需要使用的话，需要在自己的项目里面执行 npm i edpx-bcs 才可以调用 BcsUploaderProcessor
