### ISSUE TITLE
edp.amd.getModuleFile 和 edp.amd.getModuleId 和 ModuleCompiler 配合工作的问题

### ISSUE THREAD

**Issue by leeight** [ecomfe/edp-build#85]
今天发现的一个项目中的case，简化一下，是这样子的：

**module.conf**的内容

```
{
    "baseUrl": "./src",
    "paths": {
        "ui": "ui/js"
    }
}
```

对于`src/ui/js/widgets/banner.js`这个文件来说，因为有`paths`的存在，导致`edp.amd.getModuleId`通过文件路径计算模块Id的时候，返回了两个Id：`ui/js/widgets/banner` 和 `ui/widgets/banner`。

我理解这2个Id应该都是合法的才对吧？

如果这2个Id都是合法的，那么 `ui/widgets/banner` 貌似可以计算出正确的路径，但是 `ui/js/widgets/banner`  是算不出来的 :-(

现在问题来了，当 ModuleCompiler 拿到2个Id之后，它应该选择用哪一个作为入口来处理呢？

**Comment by leeight** [comment]
看了看其它的 test case，如果配置的 `module.conf` 内容是这样子的:

```
{
    "baseUrl": "./src",
    "paths": {
        "hello": "bar/hello"
    }
}
```

那么对于文件`src/bar/hello.js`来说，返回的两个Id `hello` 和 `bar/hello` 貌似都是可以的。

**Comment by otakustay** [comment]
对于第一个示例，`ui/js/widgets/banner`这个id是不行的，由于`path`的存在，路径会被解释为`ui/js/js/widgets/banner`，所以不用去处理这个情况吧

**Comment by leeight** [comment]
所以对于第二个配置，返回了  `['hello', 'bar/hello']` 都是合法的，可以正常处理的。
但是对于第一个配置，返回了 `['ui/js/widgets/banner', 'ui/widgets/banner']` 这里面就有一个是无法处理的情况。

怎么判断呢？再遍历一次 Module Id List，看看是不是能再把文件找回来？

**Comment by otakustay** [comment]
看上去应该是这样，`path`中的key和value如果不是尾匹配，则只能返回一个id，全的那个应该被丢掉

`bar: 'foo/bar'`这是尾匹配，`foo: 'foo/bar'`这个不是

**Comment by leeight** [comment]
我想了想，貌似应该判断前缀。如果 `value.indexOf(key + '/) === 0` 的话，那么开发状态下，代码中应该不会出现 `value` 前缀的模块Id，不然肯定会挂掉的吧。

所以如果出现了这种情况，那么就不要返回2个Id了（也就是舍弃掉以 baseUrl 计算出来的那个模块Id）

**Comment by otakustay** [comment]
想了几个case，似乎就是这样的，丢掉`baseUrl`的那个就行了

**Comment by leeight** [comment]
cc @erik168

**Comment by leeight** [comment]
+ edp-core@1.0.29
+ edp-build@1.0.15-beta.12
