### ISSUE TITLE
LessCompiler运行后，文件依然是less后缀名

### ISSUE THREAD

**Issue by badplum** [ecomfe/edp-build#89]
在LessCompiler的processor完成后，在后续processor用file筛选后缀为css文件找不到，还是需要使用less后缀。
调试发现LessCompiler后文件还是less后缀名，到最后输出的时候才改成css。
这个符合设计预期么？

**Comment by leeight** [comment]
是的，符合语气。`FileInfo`的`outputPath`决定了最后输出的内容。

**Comment by badplum** [comment]
OK，了解了。谢谢
