### ISSUE TITLE
md5-renamer 遇到带空格的路径，没有去空格导致windows下输出错误

### ISSUE THREAD

**Issue by kekee000** [ecomfe/edp-build#91]
考虑这样的场景

    background: url(./img/logo.png[空格]) 0 0 no-repeat;

在执行renamer的时候会用  ‘src/img/logo.png[空格]’ 替换，注意空格没有被去掉，
没有相应的导出接口进行修正，导致windows下文件名字生成错误

**Comment by leeight** [comment]
DONE
